Repository HelloCuriosity/model-forge, pull requests merged in 2022-03, with the labels that each got.

#155 Fix StringProvider treatment of invalid wordCount
  README.md
  forge-core/src/main/kotlin/io/github/hellocuriosity/providers/StringProvider.kt
  forge-core/src/test/kotlin/io/github/hellocuriosity/providers/StringProviderTest.kt
Labels: bug :bug:

#149 [Feature] Map Collection Support
  CHANGELOG.MD
  README.md
  forge-core/src/main/kotlin/io/github/hellocuriosity/ModelForge.kt
  forge-test-utils/src/main/kotlin/io/github/hellocuriosity/TestObject.kt
Labels: feature :moneybag:

#162 [Enhancement] Better Output Message in attempt
  CHANGELOG.MD
  forge-core/src/main/kotlin/io/github/hellocuriosity/TryExt.kt
Labels: enhancement :sparkles:

#156 Remove custom provider and use javax Provider
  .github/workflows/main.yml
  CHANGELOG.MD
  README.md
  build.gradle.kts
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/Dependencies.kt
  forge-core/build.gradle.kts
  forge-core/src/main/kotlin/io/github/hellocuriosity/Forgery.kt
  forge-core/src/main/kotlin/io/github/hellocuriosity/ModelForge.kt
  forge-core/src/main/kotlin/io/github/hellocuriosity/ModelForgeKotlin.kt
  forge-core/src/main/kotlin/io/github/hellocuriosity/providers/Provider.kt
  forge-core/src/test/kotlin/io/github/hellocuriosity/TestProviderObject.kt
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
Labels: enhancement :sparkles:

#163 Publish sources, solves #161
  forge-core/build.gradle.kts
Labels: documentation :book:, enhancement :sparkles:

#164 [Release] Prepare Version 0.9.0
  CHANGELOG.MD
  MIGRATION.md
  README.md
  forge-core/src/main/kotlin/io/github/hellocuriosity/Forgery.kt
  forge-core/src/main/kotlin/io/github/hellocuriosity/ModelForgeKotlin.kt
Labels: release :tada:
